trigger:
- main  # or master branch

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'azure-service-connection'
  inputs:
    azureSubscription: 'Your-Service-Connection-Name'   # Change this
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "Deploying Bicep template..."
      az deployment group create \
        --resource-group Dev \
        --template-file main.bicep

