trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureCLI@2
  displayName: 'Deploy Bicep Infrastructure to Azure'
  inputs:
    azureSubscription: 'azure-service-connection'   # 👈 your existing service connection
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "🔹 Validating Bicep file..."
      az bicep build --file infra/main.bicep

      echo "🚀 Starting deployment to Resource Group: Dev"

      az deployment group create \
        --resource-group Dev \                       # 👈 your existing resource group
        --template-file infra/main.bicep \
        --parameters @infra/parameters.json \
        --output table

