trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  location: 'CentralIndia'
  resourceGroup: 'Dev'
  prefix: 'demo'

stages:
- stage: DeployInfrastructure
  displayName: "Deploy Azure Infrastructure via Bicep"
  jobs:
  - job: Deploy
    displayName: "Deploy all resources"
    steps:
    - checkout: self

    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Creating Resource Group if not exists..."
          az group create --name ${{ variables.resourceGroup }} --location ${{ variables.location }}

          echo "Deploying Bicep Template..."
          az deployment group create \
            --resource-group ${{ variables.resourceGroup }} \
            --template-file infra/main.bicep \
            --parameters prefix=${{ variables.prefix }} location=${{ variables.location }}
