trigger:
- main

pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  displayName: 'Deploy Bicep Infrastructure'
  inputs:
    azureSubscription: 'azure-service-connection'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "🔹 Starting Bicep deployment..."
      RG_NAME="Dev"
      LOCATION="CentralIndia"
      TEMPLATE_FILE="$(System.DefaultWorkingDirectory)/infra/main.bicep"
      PARAM_FILE="$(System.DefaultWorkingDirectory)/infra/parameters.json"

      echo "Using template: $TEMPLATE_FILE"
      ls -l $(dirname $TEMPLATE_FILE)

      az deployment group create \
        --resource-group $RG_NAME \
        --template-file $TEMPLATE_FILE \
        --parameters @$PARAM_FILE \
        --output table
