trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  resourceGroupName: 'Dev'
  location: 'Central India'

stages:
- stage: DeployInfra
  displayName: 'Deploy Azure Infrastructure using Bicep'
  jobs:
  - job: Deploy
    steps:
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'azure-service-connection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          echo "Deploying resources using Bicep..."

          az group create --name $resourceGroupName --location "$location"

          az deployment group create \
            --resource-group $resourceGroupName \
            --template-file main.bicep \
            --parameters administratorPassword='Poornima@12345!' \
                         adminPassword='Poori@123!' \
                         location="$location"

