# azure-pipelines.yml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  RESOURCE_GROUP: 'Dev'
  LOCATION: 'centralindia'
  BICEP_FILE: 'infra/main.bicep'

steps:
- task: AzureCLI@2
  displayName: 'Deploy Azure Infrastructure using Bicep'
  inputs:
    azureSubscription: 'azure-service-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "Deploying to resource group: $RESOURCE_GROUP"
      az group show -n $RESOURCE_GROUP || az group create -n $RESOURCE_GROUP -l $LOCATION

      echo "Starting deployment..."
      az deployment group create \
        --resource-group $RESOURCE_GROUP \
        --template-file $BICEP_FILE \
        --output json

